/**************************************************************************************************************
Developed by: Enterprise
Author: Dirceu Monteiro
Project: PROMPT
Descritpion: Class created to excute the x Calculation
Changes (Versions)
--------------------------------------------------------------------------------------------------------------
No.     Date           Author                             Descritpion
------ ---------- --------------------------------------------------------------------------------------------
1.0     10-10-2022     Dirceu Monteiro (DM)               Class Created
2.0     11-12-2022     Dirceu Monteiro (DM)               Adpated to use the case and site (lookups)
3.0     20-12-2022     Dirceu Monteiro (DM)               Adpated to use the Site id insted of the Tax Payer Number
**************************************************************************************************************/
